version: '3.7'

services:
  bot:
    image: ghcr.io/loboda4450/pingbot-telegram:d63361f983c0cd03a81db0151e7a510a38347ddf
    volumes:
      - ./config.yml:/app/config.yml:ro
      - ./utils/users-orm.sqlite:/app/utils/users-orm.sqlite
      - ./PingBot.session:/app/PingBot.session
    restart: unless-stopped